- client/src/Components/Common/Input/__snapshots__/index.test.js.snap
- client/src/Components/Common/Input/index.jsx
- client/src/Components/Common/Input/index.style.js
- client/src/Components/Common/Input/index.test.js
- client/src/Components/Common/Title/__snapshots__/index.test.js.snap
- client/src/Components/Common/Title/index.jsx
- client/src/Components/Common/Title/index.style.js
- client/src/Components/Common/Title/index.test.js
create Title component with style :
- You should pass value that represent the text inside the title .
```
<Title 
value="Bio" 
/>
```
create input component with style :
- label that represent the title of Label  .
- name that represent the name  of input .
- onChange that represent function to change value of input ( controlled component )
- type that represent the type of input .
- width that represent the width of input .  
```
<Input
label="Username"
name="username"
value={inputValue}
onChange={this.onChange}
type="text"
width="15rem"
/>
```
> static component

- server/database/dummy_data/conversation.js
> Fix conversation dummy data date field name

- package-lock.json
- server/__test__/api/login.js
- server/__test__/api/register.js
- server/__test__/database/queries/login.js
- server/__test__/validation/register.js
- server/database/queries/login.js
- server/router/controllers/index.js
- server/router/controllers/login.js
- server/router/controllers/validate_password.js
> Login back

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Components/Common/Header/__snapshots__/index.test.js.snap
- client/src/Components/Common/Header/index.style.js
- client/src/Components/Common/Input/__snapshots__/index.test.js.snap
- client/src/Components/Common/Input/index.jsx
- client/src/Components/Common/Title/__snapshots__/index.test.js.snap
- client/src/Components/Common/Title/index.style.js
- client/src/Components/Pages/Login/__snapshots__/login.test.js.snap
- client/src/Components/Pages/Login/index.jsx
- client/src/Components/Pages/Login/index.style.js
- client/src/Components/Pages/Login/login.test.js
- client/src/Components/Routs/index.js
- client/src/Components/Routs/index.style.js
Relates #19 
I also fixed eslint in client side
change minor things in common components style
> Login front-end

- client/package.json
- client/src/App.css
- client/src/Components/Common/Input/index.jsx
- client/src/Components/Common/Title/__snapshots__/index.test.js.snap
- client/src/Components/Common/Title/index.style.js
- client/src/Components/Pages/Conversations/__snapshots__/index.test.js.snap
- client/src/Components/Pages/Conversations/index.jsx
- client/src/Components/Pages/Conversations/index.style.js
- client/src/Components/Pages/Conversations/index.test.js
- client/src/Components/Pages/Login/__snapshots__/login.test.js.snap
- client/src/Components/Routs/index.js
- client/src/Components/Routs/index.style.js
- server/database/queries/conversation.js
- server/router/controllers/conversations.js
- server/router/controllers/index.js
> Conversations

- client/package-lock.json
- client/package.json
- client/src/Components/Pages/Advice/__snapshots__/index.test.js.snap
- client/src/Components/Pages/Advice/index.js
- client/src/Components/Pages/Advice/index.style.js
- client/src/Components/Pages/Advice/index.test.js
- client/src/Components/Routs/index.js
- client/src/assets/downArrow.svg
> Advice section

- server/__test__/api/dashboard.js
- server/__test__/database/queries/dashboard.js
- server/database/queries/dashboard_statistics.js
- server/router/controllers/dashboard.js
- server/router/controllers/index.js
Relates #81 
get the dashboard statistics for the logged in user and summarize them and group by days and by mood status
> Dashboard Back-End

- server/__test__/database/queries/conversation.js
- server/database/queries/conversation.js
adds a query test to conversations.js 
relates #28
> query test added

- package.json
- server/router/bot/fulfillment.js
- server/router/bot/messages.js
- server/router/bot/weekdayFulfillment.js
Relates to #85 
Will need thorough user testing to make sure all the flows are connected properly, but you should now be able to complete an entire conversation following the weekday flow (#3 )
All intents are in the WeekdayStart, plus some general intents that will be used across multiple flows (e.g. Bullied, GeneralOther, Friend-Issue, Work-Issue)
> Weekday dialogflow

- client/src/App.js
- client/src/Components/Routs/index.js
- server/__test__/database/queries/conversation.js
Relates #89 , #21 
* Store the user info in the local storage, and retrieve them when the app is `DidMount` again
* protecting private routes and redirect the user to the proper page.
> Store user info in local storage and protect private routes

- client/src/Components/Common/Menu/index.jsx
- client/src/Components/Common/Menu/index.style.js
- client/src/Components/Common/Title/__snapshots__/index.test.js.snap
- client/src/Components/Common/Title/index.style.js
- client/src/Components/Pages/Advice/__snapshots__/index.test.js.snap
- client/src/Components/Pages/Advice/index.style.js
- client/src/Components/Pages/Conversations/__snapshots__/index.test.js.snap
- client/src/Components/Pages/Login/__snapshots__/login.test.js.snap
- client/src/Components/Pages/SignUp/__snapshots__/index.test.js.snap
- client/src/Components/Routs/index.style.js
> Menu links

- client/src/Components/Pages/Chat/index.css
- client/src/Components/Pages/Chat/index.jsx
- client/src/Components/Pages/Chat/index.style.js
- package.json
- server/router/bot/fulfillment.js
- server/router/bot/generalFulfillment.js
- server/router/bot/weekdayFulfillment.js
- Further styling of chat window - #95 
- Add card handling in chat - #101 
- Fix fulfillment bug - #100 
- All flows should now end with user able to add more thoughts or check out other areas of the platform - #27
> Chat development

- client/src/Components/Pages/Chat/index.jsx
- package-lock.json
- package.json
- server/__test__/bot/mail_builder.js
- server/__test__/bot/store_messages.js
- server/__test__/database/queries/check_support_keywords.js
- server/__test__/database/queries/get_threat_conversation.js
- server/__test__/database/schema/support_keywords.js
- server/database/dummy_data/index.js
- server/database/dummy_data/reset_DB.js
- server/database/dummy_data/support_keyword.js
- server/database/models/SupportKeyword.js
- server/database/queries/check_support_keywords.js
- server/database/queries/get_threat_conversation.js
- server/router/bot/index.js
- server/router/bot/mail_builder.js
- server/router/bot/messages.js
- server/router/bot/storeMessages.js
- server/router/bot/support_keywords.js
Relates #32 
create a `SupportKeywords` collection and add a dummy data (need to be changed with real data after PO response)
when the student sends a message that contains some words that means he/she need immediate support, the app will detect that threat and send an email to the staff with the student info and the threat details, also it will show a popup message to the student to encourage him/her to ask for help in the school mental health guidance.
to test this branch locally you need to add these parameters into `.env` file:
```js
EMAIL = nightingalewellbeing@gmail.com
EMAIL_PASSWORD = <Email Password> // put the right one here without '<' & '>'
STAFF = First name <firstemail@mail.com>, Second name <secondemail@mail.com> // keep this format (don't remove '<' & '>')
``` 
@dupreesi …
> Immediate support

- client/package.json
- client/src/Components/Pages/Chat/index.jsx
- server/__test__/api/bot.startChat.js
- server/__test__/bot/store_messages.js
- server/database/queries/decideFlow.js
- server/router/bot/dialogflowSessionClient.js
- server/router/bot/index.js
- server/router/bot/messages.js
- server/router/bot/startChat.js
- server/router/bot/storeMessages.js
Relates issue #103 
It now checks if it is a weekday and if so triggers an event to start the weekday flow. 
It also will trigger an event to start the weekend flow, but this needs to be fully written in dialogflow! Initial start created with 'WeekendStart' intent
> Set up event triggers for starting the conversation

- client/src/Components/Common/Header/index.jsx
- client/src/Components/Common/Header/index.test.js
- client/src/Components/Common/Menu/index.jsx
- client/src/Components/Common/Menu/index.test.js
- client/src/Components/Routs/index.js
- server/__test__/api/logout.js
- server/router/controllers/index.js
- server/router/controllers/logout.js
> Logout front-end and back-end

- client/src/Components/Pages/ConversationMessages/index.jsx
- package.json
- server/database/queries/messages.js
- server/database/queries/update_mood.js
- server/router/bot/dialogflowSessionClient.js
- server/router/bot/messages.js
- server/router/bot/weekdayFulfillment.js
- server/router/controllers/index.js
> Mood store / update

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Components/Common/Header/index.jsx
- client/src/Components/Common/Menu/index.jsx
- client/src/Components/Routs/index.js
Add expire date for token and remove it from client when it expired
Relates #113
> Add expire date for token

- client/src/App.js
- client/src/Components/Pages/Chat/index.jsx
- server/database/queries/decideFlow.js
- server/database/queries/getUserDetails.js
- server/database/queries/makeDaysArray.js
- server/database/queries/storeParams.js
- server/router/bot/dialogflowSessionClient.js
- server/router/bot/fulfillment.js
- server/router/bot/getUserInfo.js
- server/router/bot/index.js
- server/router/controllers/userInfo.js
>relates #135 
- finishes the registration for a user
- when user registers initial conversation with bot starts asking for parameters bday, subject, subject days
- as soon as user answers those questions a backend function stores the new infos in the database and a frontend function runs that triggers a get request to get the freshly inserted values and updates the localStorage AppState accordingly. This is required to keep the conversation going triggering a new intend.
> Update app state

- server/router/controllers/login.js
- server/router/controllers/register.js
> Add maxAge to cookies

- client/src/Components/Common/Header/__snapshots__/index.test.js.snap
- client/src/Components/Common/Header/index.style.js
> Fix the z-index for the Header and update test

- client/src/Components/Pages/Chat/index.css
- client/src/Components/Pages/ConversationMessages/__snapshots__/index.test.js.snap
- client/src/Components/Pages/ConversationMessages/index.jsx
- client/src/Components/Pages/ConversationMessages/index.style.js
- client/src/Components/Pages/Conversations/index.jsx
- client/src/Components/Pages/Landing/index.jsx
- server/__test__/bot/store_messages.js
- server/__test__/database/queries/get_threat_conversation.js
- server/__test__/database/schema/message.js
- server/database/dummy_data/message.js
- server/database/queries/conversation.js
- server/database/queries/messages.js
- server/router/controllers/messages.js
Sorted out this bug #145 
Also added some extra tweaks:
- landing page to move onto onboarding screen automatically
- chat bubbles to fade in for nicer UI
**NOTE: make sure to rebuild data**
Ramy: **also be sure to use the same M.lab DB URL with Heroku to update the conversation mood for same user**
> Few more bug fixes

- server/router/bot/messages.js
Relates #150 
This would be solved the fallback issue. so when the user input something wrong. and fallback intent been triggered and then input the correct value it will trigger the last intent before the fallback.
> fix conversation context

- server/__test__/database/queries/decideFlow.js
- server/database/queries/decideFlow.js
- server/router/bot/dialogflowSessionClient.js
- server/router/bot/messages.js
- server/router/bot/startChat.js
Fix the initial conversation issue
> fix the initial conversation
